server:
  port: 8082
spring:
  application:
    name: fisher-transaction-alipay-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://172.16.1.195:3306/fisher?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: bailian
    password: bailian
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  profiles:
    active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.1.212:8848